language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/sde

env:
    - arch=x86_64  subset=sse2
    - arch=x86_64  subset=sse4
    - arch=x86_64  subset=avx
    - arch=x86_64  subset=avx2
    - arch=x86_64  subset=avx512
    - arch=x86_64  subset=knl
    - arch=aarch64 subset=neon

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

# The whitespace in "env:" lines must match the definition above!
matrix:
  exclude:
    - env: arch=x86_64  subset=avx512
      os: osx
    - env: arch=x86_64  subset=knl
      os: osx
    - env: arch=aarch64 subset=neon
      os: osx
  allow_failures:
      # GCC on OS X sometimes times out. Those spurious failures are not useful
      # and GCC is tested well enough on Linux anyway. CDash will also show failures
      # if they are submitted.
    - os: osx
      compiler: gcc
    - env: arch=aarch64 subset=neon

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty

install:
    - case "$TRAVIS_OS_NAME-$CXX-$arch" in
        linux-g++-x86_64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install g++-6 binutils -y &&
          export CXX=g++-6 CC=gcc-6;;
        linux-clang++-x86_64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
          sudo tee /etc/apt/sources.list.d/llvm.list <<< "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" &&
          sudo apt-get update -q &&
          sudo apt-get install clang-4.0 libstdc++-6-dev -y &&
          export CXX=clang++-4.0 CC=clang-4.0;;
        osx-g++-x86_64)
          brew update &&
          brew install gcc6 &&
          export CXX=g++-7 CC=gcc-7;;
        osx-clang++-x86_64)
          wget http://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz &&
          tar xf clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz &&
          cd clang+llvm-4.0.0-x86_64-apple-darwin &&
          export CXX=$PWD/bin/clang++ CC=$PWD/bin/clang &&
          export LDFLAGS="-L$PWD/lib -Wl,-rpath,$PWD/lib" &&
          export CPPFLAGS=-I$PWD/include &&
          cd ..;;
        linux-g++-aarch64)
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install -y g++-5-aarch64-linux-gnu &&
          export CXX=aarch64-linux-gnu-g++-5 CC=aarch64-linux-gnu-gcc-5 CMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-linux.cmake;;
        linux-clang++-aarch64)
          wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
          sudo tee /etc/apt/sources.list.d/llvm.list <<< "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" &&
          sudo apt-get update -q &&
          sudo apt-get install -y clang-4.0 &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial main' &&
          sudo add-apt-repository -y 'deb http://de.archive.ubuntu.com/ubuntu/ xenial-updates main' &&
          sudo apt-get update -q &&
          sudo apt-get install -y libstdc++-5-dev-arm64-cross gcc-5-aarch64-linux-gnu &&
          export CPATH=/usr/aarch64-linux-gnu/include &&
          export CXX="clang++-4.0 -target aarch64-linux-gnu" CC="clang-4.0 -target aarch64-linux-gnu" &&
          export CMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-linux.cmake;;
      esac

before_script:
    # ptrace_scope=0 is required on Ubuntu for SDE to work
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope;
      fi
    - $CXX --version
    - cmake --version
    - export dashboard_model=Experimental
    - export build_type=Release
    - export NUMBER_OF_PROCESSORS=2

script:
    - ctest -VV -S scripts/test.cmake

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net##Vc"
        on_success: change # [always|never|change] # default: always
        on_failure: always # [always|never|change] # default: always
        use_notice: true
        skip_join: true
